# Generated by Django 2.2 on 2021-01-06 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientname', models.CharField(max_length=20)),
                ('doc_prescription', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.IntegerField(primary_key=True, serialize=False)),
                ('room_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization_list', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SlotRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_address', models.TextField(max_length=50)),
                ('patient_email', models.EmailField(max_length=50)),
                ('patient_age', models.IntegerField()),
                ('patient_symptom', models.TextField(max_length=100)),
                ('doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.Doctor')),
                ('patient_detail_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SlotAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slotdoctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.Doctor')),
                ('slotpatient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('slotroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.Room')),
                ('slotspecialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.Specialization')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.Specialization'),
        ),
    ]
