# Generated by Django 2.2 on 2021-01-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotrequest',
            name='doctor_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='slotrequest',
            name='patient_detail_name',
            field=models.CharField(max_length=50),
        ),
    ]
