# Generated by Django 2.2 on 2021-01-06 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_auto_20210106_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slotrequest',
            old_name='patient_detail_name',
            new_name='patient_name',
        ),
    ]
