# Generated by Django 2.2 on 2021-01-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0003_auto_20210106_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotrequest',
            name='patient_symptom',
            field=models.TextField(max_length=50),
        ),
    ]
