# Generated by Django 3.1.4 on 2021-01-07 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0006_auto_20210107_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='patientsymptom',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
