# Generated by Django 3.1.4 on 2021-01-07 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0007_prescription_patientsymptom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotrequest',
            name='patient_age',
        ),
    ]
