# Generated by Django 2.2 on 2021-01-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0010_auto_20210108_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotrequest',
            name='patientsymptom',
            field=models.CharField(max_length=50),
        ),
    ]
