# Generated by Django 2.2 on 2021-01-09 01:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0012_auto_20210108_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotallocation',
            name='slotdate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slotallocation',
            name='slotgender',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
